#!/bin/sh
# 
# This script will host commands shortened into functions as to avoid all that annyoying typing in the command line.

declare -A commands_and_desc
commands_and_desc["nd_test_app"]="nd_test_app appname.path.to.test.method"
commands_and_desc["nd_test_utility_app"]="nd_test_utlity_app appname.path.to.test.method"
commands_and_desc["nd_test_web_app"]="nd_test_web_app appname.path.to.test.method"
commands_and_desc["nd_test_newsworm"]="nd_test_newsworm unitests.path.to.subtests"
commands_and_desc["nd_test_newsworm_core"]="nd_test_newsworm_core path.to.subtests"
commands_and_desc["nd_test"]="nd_test_ test any path in newsline project"

help(){
    printf '\n\n\n\033[92mThe newsline project management commands:\n'
	for i in "${!commands_and_desc[@]}"
	do
	  printf "\n\t  \033[1m\033[94m$i\033[0m : \033[95m${commands_and_desc[$i]}\033[0m \n"
	done
	printf "\n\n\n"
}

# No database test runner
nd_test(){
	if [ ! -z "$1" -a "$1" != " " ]; then
		printf "\n\033[95mTesting for newsline.$1\033[0m\n"
  		eval "python3 ../manage.py test newsline.$1 --testrunner=newsline.scripts.no_db_test_runner.NoDbTestRunner"
	else
		echo "You have to specify the test path [without using newsline.]";
	fi	
}

nd_test_app(){
	if [ ! -z "$1" -a "$1" != " " ]; then
		printf "\n\033[95mTesting for newsline.apps.$1\033[0m\n"
  		eval "python3 ../manage.py test newsline.apps.$1 --testrunner=newsline.scripts.no_db_test_runner.NoDbTestRunner"
	else
		echo "You have to specify the test path [without using newsline.apps.]";
	fi	
}

nd_test_utility_app(){
	if [ ! -z "$1" -a "$1" != " " ]; then
  		eval ". use nd_test_app utility.$1 --testrunner=newsline.scripts.no_db_test_runner.NoDbTestRunner"
	else
		echo "You have to specify the test path [without using newsline.apps.utility]";
	fi
}

nd_test_web_app(){
	if [ ! -z "$1" -a "$1" != " " ]; then
  		eval ". use nd_test_app web.$1 --testrunner=newsline.scripts.no_db_test_runner.NoDbTestRunner"
	else
		echo "You have to specify the test path [without using newsline.apps.web]";
	fi
}

nd_test_newsworm(){
	if [ ! -z "$1" -a "$1" != " " ]; then
  		eval ". use nd_test_web_app newsworm.unittests.$1 --testrunner=newsline.scripts.no_db_test_runner.NoDbTestRunner"
	else
		echo "You have to specify the test path [without using newsline.apps.web.newsworm.unitests]";
	fi
}

nd_test_newsworm_core(){
	if [ ! -z "$1" -a "$1" != " " ]; then
  		eval ". use nd_test_newsworm core.$1 --testrunner=newsline.scripts.no_db_test_runner.NoDbTestRunner"
	else
		echo "You have to specify the test path [without using newsline.apps.web.newsworm.unittests.core]";
	fi
}
$@