# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePrototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('regex', models.CharField(max_length=255)),
                ('dom_path', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryPrototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('regex', models.CharField(max_length=255)),
                ('dom_path', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_url', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='categoryprototype',
            name='parent_website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryprototype', to='newsworm.NewsWebsite'),
        ),
        migrations.AddField(
            model_name='articleprototype',
            name='parent_website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleprototype', to='newsworm.NewsWebsite'),
        ),
    ]
